name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository's code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Run Gulp tasks
      run: npx gulp build  # Run your Gulp build task

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: dist  # Path to the build artifacts

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: github-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4